# Generated by Django 4.0.3 on 2022-03-30 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinDetails',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_id', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=254)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='InboxDetails',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_id', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=254)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='JunkDetails',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_id', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=254)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='SentDetails',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_id', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=254)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
    ]
