# Generated by Django 4.0.3 on 2022-04-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_alter_bindetails_uid_alter_inboxdetails_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindetails',
            name='from_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inboxdetails',
            name='from_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='junkdetails',
            name='from_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sentdetails',
            name='to_id',
            field=models.CharField(max_length=200),
        ),
    ]
