# Generated by Django 4.0.3 on 2022-04-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0005_delete_bindetails_delete_inboxdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('from_id', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=254)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='InboxDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('from_id', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=254)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='JunkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('from_id', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=254)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='SentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('to_id', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=254)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
    ]
